# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1855, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")



        self.groupBox_camimgsave = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_camimgsave.setGeometry(QtCore.QRect(660, 585, 363, 247))
        self.groupBox_camimgsave.setObjectName("groupBox_camimgsave")

        self.groupBox_camimgsave1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_camimgsave1.setGeometry(QtCore.QRect(1028, 585, 363, 247))
        self.groupBox_camimgsave1.setObjectName("groupBox_camimgsave1")

        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(388, 560, 263, 270))
        self.tabWidget.setObjectName("tabWidget")

        self.tabWidget.setStyleSheet(
            """QTabWidget::pane{border-width:1px;border-color:#DCDCDC;border-style: solid;background-color:#F0F0F0}
                QTabBar::tab{border-width:1px;border-color:#DCDCDC; font: 15px ; height: 30px;width: 100px;border-top-left-radius: 3px;border-top-right-radius: 3px;}
                QTabBar::tab:first:selected{ border-bottom-color: #FDFDFD;border-style: solid;margin-left: 0; margin-right: 0;color: black;background-color:#FDFDFD;}
                QTabBar::tab:first:!selected {border-style: solid;color: black;background-color:#F0F0F0}
                QTabBar::tab:last:selected{ border-style: solid;margin-left: 0; margin-right: 0;color: black;background-color:#FDFDFD}
                QTabBar::tab:last:!selected {border-style: solid;color: black;background-color:#F0F0F0}
                """
        )

        self.tab_DMD = QtWidgets.QWidget()
        self.tab_DMD.setObjectName("tab_DMD")
        self.tabWidget.addTab(self.tab_DMD, "DMD控制")

        self.tab_SLM = QtWidgets.QWidget()
        self.tab_SLM.setObjectName("tab_SLM")
        self.tabWidget.addTab(self.tab_SLM, "SLM控制")

        self.tabWidget_Imgseqandopen = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget_Imgseqandopen.setGeometry(QtCore.QRect(10, 560, 370, 270))
        self.tabWidget_Imgseqandopen.setObjectName("tabWidget_Imgseqandopen")

        self.tabWidget_Imgseqandopen.setStyleSheet(
            """QTabWidget::pane{border-width:1px;border-color:#DCDCDC;border-style: solid;background-color:#F0F0F0}
                       QTabBar::tab{border-width:1px;border-color:#DCDCDC; font: 15px ; height: 30px;width: 183px;border-top-left-radius: 3px;border-top-right-radius: 3px;}
                       QTabBar::tab:first:selected{ border-bottom-color: #FDFDFD;border-style: solid;margin-left: 0; margin-right: 0;color: black;background-color:#FDFDFD;}
                       QTabBar::tab:first:!selected {border-style: solid;color: black;background-color:#F0F0F0}
                       QTabBar::tab:last:selected{ border-style: solid;margin-left: 0; margin-right: 0;color: black;background-color:#FDFDFD}
                       QTabBar::tab:last:!selected {border-style: solid;color: black;background-color:#F0F0F0}
                       """
        )

        self.tab_ImgGene = QtWidgets.QWidget()
        self.tab_ImgGene.setObjectName("tab_ImgGene")
        self.tabWidget_Imgseqandopen.addTab(self.tab_ImgGene, "生成新图片至图片序列")

        self.tab_ImgOpen = QtWidgets.QWidget()
        self.tab_ImgOpen.setObjectName("tab_ImgOpen")
        self.tabWidget_Imgseqandopen.addTab(self.tab_ImgOpen, "打开已有图片至图片序列")



        self.tabWidget_CAM2andPM = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget_CAM2andPM.setGeometry(QtCore.QRect(933, 5, 920, 600))
        self.tabWidget_CAM2andPM.setTabPosition(self.tabWidget_CAM2andPM.South)
        self.tabWidget_CAM2andPM.setObjectName("tabWidget_CAM2andPM")

        self.tabWidget_CAM2andPM.setStyleSheet(
            """QTabWidget::pane{border-width:1px;border-color:#DCDCDC;border-style: solid;background-color:#F0F0F0}
               QTabWidget::tab-bar { alignment: right; } 
                       QTabBar::tab{border-width:1px;border-color:#DCDCDC; font: 15px ; height: 30px;width: 80px;border-top-left-radius: 3px;border-top-right-radius: 3px;}
                       QTabBar::tab:first:selected{ border-bottom-color: #FDFDFD;border-style: solid;margin-left: 0; margin-right: 0;color: black;background-color:#FDFDFD;}
                       QTabBar::tab:first:!selected {border-style: solid;color: black;background-color:#F0F0F0}
                       QTabBar::tab:last:selected{ border-style: solid;margin-left: 0; margin-right: 0;color: black;background-color:#FDFDFD}
                       QTabBar::tab:last:!selected {border-style: solid;color: black;background-color:#F0F0F0}
                       """
        )

        self.tab_CAM2 = QtWidgets.QWidget()
        self.tab_CAM2.setObjectName("tab_CAM2")
        self.tabWidget_CAM2andPM.addTab(self.tab_CAM2, "ccd2")

        self.tab_PM = QtWidgets.QWidget()
        self.tab_PM.setObjectName("tab_PM")
        self.tabWidget_CAM2andPM.addTab(self.tab_PM, "功率计")



        self.label_PMinf = QtWidgets.QLabel(self.tab_PM)
        self.label_PMinf.setGeometry(QtCore.QRect(30, 149, 90, 31))
        self.label_PMinf.setObjectName("label_PMinf")

        self.label_PMdev = QtWidgets.QLabel(self.tab_PM)
        self.label_PMdev.setGeometry(QtCore.QRect(30, 50, 90, 31))
        self.label_PMdev.setObjectName("label_PMdev")

        self.label_PMwavelength = QtWidgets.QLabel(self.tab_PM)
        self.label_PMwavelength.setGeometry(QtCore.QRect(30, 100, 90, 31))
        self.label_PMwavelength.setObjectName("label_PMwavelength")

        self.label_PMwavelengthnm = QtWidgets.QLabel(self.tab_PM)
        self.label_PMwavelengthnm.setGeometry(QtCore.QRect(210, 100, 90, 31))
        self.label_PMwavelengthnm.setObjectName("label_PMwavelengthnm")

        self.groupBox_powerdis = QtWidgets.QGroupBox(self.tab_PM)
        self.groupBox_powerdis.setGeometry(QtCore.QRect(30, 200, 710, 350))
        self.groupBox_powerdis.setObjectName("groupBox_powerdis")

        self.label_PMwl2dis = QtWidgets.QLabel(self.tab_PM)
        self.label_PMwl2dis.setGeometry(QtCore.QRect(40, 100, 500, 330))
        self.label_PMwl2dis.setStyleSheet(  # 'font-size: 250px;'#
            "  font: 15pt \"黑体\";"
            "text-align: center;"
        )

        self.label_PMwl2dis.setObjectName("label_PMwl2dis")

        self.label_PMmeasure = QtWidgets.QLabel(self.groupBox_powerdis)
        self.label_PMmeasure.setGeometry(QtCore.QRect(30, 10, 690, 330))
        self.label_PMmeasure.setStyleSheet(#'font-size: 250px;'#
                                           "  font: 80pt \"黑体\";"
                                           "text-align: center;"
                                           )

        self.label_PMmeasure.setObjectName("label_PMmeasure")

        self.pushButton_refreshPMdev = QtWidgets.QPushButton(self.tab_PM)
        self.pushButton_refreshPMdev.setGeometry(QtCore.QRect(750, 50, 120, 31))
        self.pushButton_refreshPMdev.setObjectName("pushButton_refreshPMdev")

        self.pushButton_connectPMdev = QtWidgets.QPushButton(self.tab_PM)
        self.pushButton_connectPMdev.setGeometry(QtCore.QRect(750, 100, 120, 31))
        self.pushButton_connectPMdev.setObjectName("pushButton_connectPMdev")

        self.pushButton_disconnectPMdev = QtWidgets.QPushButton(self.tab_PM)
        self.pushButton_disconnectPMdev.setGeometry(QtCore.QRect(750, 450, 120, 31))
        self.pushButton_disconnectPMdev.setObjectName("pushButton_disconnectPMdev")


        self.comboBox_PMlist = QtWidgets.QComboBox(self.tab_PM)
        self.comboBox_PMlist.setGeometry(QtCore.QRect(100, 50, 640, 31))
        self.comboBox_PMlist.setObjectName("comboBox_PMlist")

        self.comboBox_PMwavelength = QtWidgets.QComboBox(self.tab_PM)
        self.comboBox_PMwavelength.setGeometry(QtCore.QRect(100, 100, 100, 31))
        self.comboBox_PMwavelength.setObjectName("comboBox_PMwavelength")
        self.comboBox_PMwavelength.addItem("350")
        self.comboBox_PMwavelength.addItem("517")
        self.comboBox_PMwavelength.addItem("633")
        self.comboBox_PMwavelength.addItem("980")
        self.comboBox_PMwavelength.addItem("1064")

















        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 40, 683, 512))
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView.setObjectName("graphicsView")

        self.graphicsView1 = QtWidgets.QGraphicsView(self.tab_CAM2)
        self.graphicsView1.setGeometry(QtCore.QRect(10, 40, 683, 512))
        self.graphicsView1.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView1.setObjectName("graphicsView1")


        self.label_BlockW = QtWidgets.QLabel(self.tab_ImgGene)
        self.label_BlockW.setGeometry(QtCore.QRect(20, 34, 60, 135))
        self.label_BlockW.setObjectName("label_BlockW")

        self.label_PreImgGenetext = QtWidgets.QLabel(self.tab_ImgGene)
        self.label_PreImgGenetext.setGeometry(QtCore.QRect(30, 149, 90, 31))
        self.label_PreImgGenetext.setObjectName("label_PreImgGenetext")

        self.label_ImgGeneinf = QtWidgets.QLabel(self.tab_ImgGene)
        self.label_ImgGeneinf.setGeometry(QtCore.QRect(160, 85, 90, 31))
        self.label_ImgGeneinf.setObjectName("label_label_ImgGeneinf")

        self.label_PreImgGene = QtWidgets.QLabel(self.tab_ImgGene)
        self.label_PreImgGene.setGeometry(QtCore.QRect(170, 151, 120, 31))
        self.label_PreImgGene.setObjectName("label_PreImgGene")

        self.label_PreImgOpen = QtWidgets.QLabel(self.tab_ImgOpen)
        self.label_PreImgOpen.setGeometry(QtCore.QRect(170, 151, 120, 31))
        self.label_PreImgOpen.setObjectName("label_PreImgOpen")

        self.pushButton_InitializetheDMD = QtWidgets.QPushButton(self.tab_DMD)
        self.pushButton_InitializetheDMD.setGeometry(QtCore.QRect(10, 20, 120, 31))
        self.pushButton_InitializetheDMD.setObjectName("pushButton_InitializetheDMD")
        # 加载至DMD内存
        self.pushButton_UptoDMD = QtWidgets.QPushButton(self.tab_DMD)
        self.pushButton_UptoDMD.setGeometry(QtCore.QRect(10, 132, 120, 31))
        self.pushButton_UptoDMD.setObjectName("pushButton_UptoDMD")
        # 清空DMD内存
        self.pushButton_cleanDMD = QtWidgets.QPushButton(self.tab_DMD)
        self.pushButton_cleanDMD.setGeometry(QtCore.QRect(133, 132, 120, 31))
        self.pushButton_cleanDMD.setObjectName("pushButton_cleanDMD")
        # DMD运行
        self.pushButton_runDMD = QtWidgets.QPushButton(self.tab_DMD)
        self.pushButton_runDMD.setGeometry(QtCore.QRect(10, 197, 120, 31))
        self.pushButton_runDMD.setObjectName("pushButton_runDMD")
        # DMD停止运行
        self.pushButton_stopDMD = QtWidgets.QPushButton(self.tab_DMD)
        self.pushButton_stopDMD.setGeometry(QtCore.QRect(133, 197, 120, 31))
        self.pushButton_stopDMD.setObjectName("pushButton_stopDMD")

        self.label_DMDIni = QtWidgets.QLabel(self.tab_DMD)
        self.label_DMDIni.setGeometry(QtCore.QRect(20, 60, 500, 16))
        self.label_DMDIni.setObjectName("label_DMDIni")

        self.label_DMDInformation = QtWidgets.QLabel(self.tab_DMD)
        self.label_DMDInformation.setGeometry(QtCore.QRect(20, 172, 500, 16))
        self.label_DMDInformation.setObjectName("label_DMDInformation")

        self.label_CCD_CatchSpeed = QtWidgets.QLabel(self.groupBox_camimgsave)
        self.label_CCD_CatchSpeed.setGeometry(QtCore.QRect(20, 80, 500, 16))
        self.label_CCD_CatchSpeed.setObjectName("CCD_CatchSpeed")

        self.label_CCD_CatchTime = QtWidgets.QLabel(self.groupBox_camimgsave)
        self.label_CCD_CatchTime.setGeometry(QtCore.QRect(20, 130, 500, 16))
        self.label_CCD_CatchTime.setObjectName("CCD_CatchTime")




        self.label_SLMInformation = QtWidgets.QLabel(self.tab_SLM)
        self.label_SLMInformation.setGeometry(QtCore.QRect(20, 60, 500, 16))
        self.label_SLMInformation.setObjectName("label_SLMInformation")

        self.pushButton_SelectSavePathofImgSeqGenerate = QtWidgets.QPushButton(
            self.tab_ImgGene
        )
        self.pushButton_SelectSavePathofImgSeqGenerate.setGeometry(
            QtCore.QRect(310, 46, 50, 31)
        )
        self.pushButton_SelectSavePathofImgSeqGenerate.setObjectName(
            "pushButton_SelectSavePathofImgSeqGenerate"
        )

        self.LineEditDistheSavePathofImgSeqGenerate = QLineEdit(self.tab_ImgGene)
        self.LineEditDistheSavePathofImgSeqGenerate.setPlaceholderText("选择图片序列保存文件夹")
        self.LineEditDistheSavePathofImgSeqGenerate.setReadOnly(True)
        self.LineEditDistheSavePathofImgSeqGenerate.setGeometry(10, 46, 290, 30)

        self.LineEditDistheSavePathofCamImg = QLineEdit(self.groupBox_camimgsave)
        self.LineEditDistheSavePathofCamImg.setPlaceholderText("选择CCD采集保存文件夹")
        self.LineEditDistheSavePathofCamImg.setReadOnly(True)
        self.LineEditDistheSavePathofCamImg.setGeometry(10, 20, 250, 30)

        self.LineEditDistheSavePathofCamImg1 = QLineEdit(self.groupBox_camimgsave1)
        self.LineEditDistheSavePathofCamImg1.setPlaceholderText("选择CCD采集保存文件夹")
        self.LineEditDistheSavePathofCamImg1.setReadOnly(True)
        self.LineEditDistheSavePathofCamImg1.setGeometry(10, 20, 250, 30)

        self.pushButton_StartCamImgSave = QtWidgets.QPushButton(
            self.groupBox_camimgsave
        )
        self.pushButton_StartCamImgSave.setGeometry(QtCore.QRect(165, 81, 120, 60))
        self.pushButton_StartCamImgSave.setObjectName("pushButton_StartCamImgSave")

        self.pushButton_StopCamImgSave = QtWidgets.QPushButton(self.groupBox_camimgsave)
        self.pushButton_StopCamImgSave.setGeometry(QtCore.QRect(175, 141, 100, 40))
        self.pushButton_StopCamImgSave.setObjectName("StopCamImgSave")

        self.pushButton_SelecttheSavePathofCamImg = QtWidgets.QPushButton(
            self.groupBox_camimgsave
        )
        self.pushButton_SelecttheSavePathofCamImg.setGeometry(
            QtCore.QRect(265, 20, 50, 31)
        )
        self.pushButton_SelecttheSavePathofCamImg.setObjectName(
            "pushButton_SelecttheSavePathofCamImge"
        )


        self.LineEditDistheSavePathofCamImg1 = QLineEdit(self.groupBox_camimgsave1)
        self.LineEditDistheSavePathofCamImg1.setPlaceholderText("选择CCD采集保存文件夹")
        self.LineEditDistheSavePathofCamImg1.setReadOnly(True)
        self.LineEditDistheSavePathofCamImg1.setGeometry(10, 20, 250, 30)

        self.LineEditDistheSavePathofCamImg1 = QLineEdit(self.groupBox_camimgsave1)
        self.LineEditDistheSavePathofCamImg1.setPlaceholderText("选择CCD采集保存文件夹")
        self.LineEditDistheSavePathofCamImg1.setReadOnly(True)
        self.LineEditDistheSavePathofCamImg1.setGeometry(10, 20, 250, 30)

        self.pushButton_StartCamImgSave1 = QtWidgets.QPushButton(
            self.groupBox_camimgsave1
        )
        self.pushButton_StartCamImgSave1.setGeometry(QtCore.QRect(165, 81, 120, 60))
        self.pushButton_StartCamImgSave1.setObjectName("pushButton_StartCamImgSave1")

        self.pushButton_StopCamImgSave1 = QtWidgets.QPushButton(self.groupBox_camimgsave1)
        self.pushButton_StopCamImgSave1.setGeometry(QtCore.QRect(175, 141, 100, 40))
        self.pushButton_StopCamImgSave1.setObjectName("StopCamImgSave1")

        self.pushButton_SelecttheSavePathofCamImg1 = QtWidgets.QPushButton(
            self.groupBox_camimgsave1
        )
        self.pushButton_SelecttheSavePathofCamImg1.setGeometry(
            QtCore.QRect(265, 20, 50, 31)
        )
        self.pushButton_SelecttheSavePathofCamImg1.setObjectName(
            "pushButton_SelecttheSavePathofCamImge1"
        )


        self.pushButton_SelectOpenPathofImgSeqGenerate = QtWidgets.QPushButton(
            self.tab_ImgOpen
        )
        self.pushButton_SelectOpenPathofImgSeqGenerate.setGeometry(
            QtCore.QRect(310, 23, 50, 31)
        )
        self.pushButton_SelectOpenPathofImgSeqGenerate.setObjectName(
            "pushButton_SelectOpenPathofImgSeqGenerate"
        )

        self.pushButton_ImgSeqOpen = QtWidgets.QPushButton(self.tab_ImgOpen)
        self.pushButton_ImgSeqOpen.setGeometry(QtCore.QRect(245, 62, 120, 31))
        self.pushButton_ImgSeqOpen.setObjectName("pushButton_ImgSeqOpen")

        self.LineEditDistheOpenPathofImgSeqGenerate = QLineEdit(self.tab_ImgOpen)
        self.LineEditDistheOpenPathofImgSeqGenerate.setPlaceholderText("选择打开图片序列文件夹")
        self.LineEditDistheOpenPathofImgSeqGenerate.setReadOnly(True)
        self.LineEditDistheOpenPathofImgSeqGenerate.setGeometry(10, 23, 290, 30)

        self.pushButton_ImgSeqGenerate = QtWidgets.QPushButton(self.tab_ImgGene)
        self.pushButton_ImgSeqGenerate.setGeometry(QtCore.QRect(245, 85, 120, 31))
        self.pushButton_ImgSeqGenerate.setObjectName("pushButton_ImgSeqGenerate")

        self.spinBox_NumofGeneImgSeq = QtWidgets.QSpinBox(self.tab_ImgGene)
        self.spinBox_NumofGeneImgSeq.setGeometry(QtCore.QRect(85, 15, 50, 27))
        self.spinBox_NumofGeneImgSeq.setMaximum(20000)
        self.spinBox_NumofGeneImgSeq.setMinimum(1)
        self.spinBox_NumofGeneImgSeq.setValue(1000)
        self.spinBox_NumofGeneImgSeq.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_NumofGeneImgSeq.setObjectName("spinBox_NumofGeneImgSeq")

        self.spinBox_BlockWofGeneImgSeq = QtWidgets.QSpinBox(self.tab_ImgGene)
        self.spinBox_BlockWofGeneImgSeq.setGeometry(QtCore.QRect(85, 87, 50, 27))
        self.spinBox_BlockWofGeneImgSeq.setMaximum(2000000)
        self.spinBox_BlockWofGeneImgSeq.setMinimum(1)
        self.spinBox_BlockWofGeneImgSeq.setValue(10)
        self.spinBox_BlockWofGeneImgSeq.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_BlockWofGeneImgSeq.setObjectName("spinBox_BlockWofGeneImgSeq")

        self.spinBox_SizeX = QtWidgets.QSpinBox(self.tab_ImgGene)
        self.spinBox_SizeX.setGeometry(QtCore.QRect(230, 15, 60, 27))
        self.spinBox_SizeX.setMaximum(20000)
        self.spinBox_SizeX.setMinimum(2)
        self.spinBox_SizeX.setValue(400)
        self.spinBox_SizeX.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_SizeX.setObjectName("spinBox_SizeX")

        self.spinBox_SizeY = QtWidgets.QSpinBox(self.tab_ImgGene)
        self.spinBox_SizeY.setGeometry(QtCore.QRect(305, 15, 60, 27))
        self.spinBox_SizeY.setMaximum(20000)
        self.spinBox_SizeY.setMinimum(2)
        self.spinBox_SizeY.setValue(400)
        self.spinBox_SizeY.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_SizeY.setObjectName("spinBox_SizeY")

        self.spinBox_DMDdisfre = QtWidgets.QSpinBox(self.tab_DMD)
        self.spinBox_DMDdisfre.setGeometry(QtCore.QRect(90, 92, 60, 27))
        self.spinBox_DMDdisfre.setMaximum(200)
        self.spinBox_DMDdisfre.setMinimum(1)
        self.spinBox_DMDdisfre.setValue(1)
        self.spinBox_DMDdisfre.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_DMDdisfre.setObjectName("spinBox_DMDdisfre")

        self.spinBox_SLMdisfre = QtWidgets.QSpinBox(self.tab_SLM)
        self.spinBox_SLMdisfre.setGeometry(QtCore.QRect(90, 92, 60, 27))
        self.spinBox_SLMdisfre.setMaximum(200)
        self.spinBox_SLMdisfre.setMinimum(1)
        self.spinBox_SLMdisfre.setValue(10)
        self.spinBox_SLMdisfre.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_SLMdisfre.setObjectName("spinBox_SLMdisfre")

        self.spinBox_SLMdislocation_x = QtWidgets.QSpinBox(self.tab_SLM)
        self.spinBox_SLMdislocation_x.setGeometry(QtCore.QRect(90, 122, 60, 27))
        self.spinBox_SLMdislocation_x.setMaximum(20000)
        self.spinBox_SLMdislocation_x.setMinimum(0)
        self.spinBox_SLMdislocation_x.setValue(800)
        self.spinBox_SLMdislocation_x.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_SLMdislocation_x.setObjectName("spinBox_SLMdislocation_x")

        self.spinBox_SLMdislocation_y = QtWidgets.QSpinBox(self.tab_SLM)
        self.spinBox_SLMdislocation_y.setGeometry(QtCore.QRect(175, 122, 60, 27))
        self.spinBox_SLMdislocation_y.setMaximum(20000)
        self.spinBox_SLMdislocation_y.setMinimum(0)
        self.spinBox_SLMdislocation_y.setValue(350)
        self.spinBox_SLMdislocation_y.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_SLMdislocation_y.setObjectName("spinBox_SLMdislocation_y")

        self.spinBox_SLMdisresloution_x = QtWidgets.QSpinBox(self.tab_SLM)
        self.spinBox_SLMdisresloution_x.setGeometry(QtCore.QRect(90, 152, 60, 27))
        self.spinBox_SLMdisresloution_x.setMaximum(20000)
        self.spinBox_SLMdisresloution_x.setMinimum(0)
        self.spinBox_SLMdisresloution_x.setValue(1920)
        self.spinBox_SLMdisresloution_x.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_SLMdisresloution_x.setObjectName("spinBox_SLMdisresloution_x")

        self.spinBox_SLMdisresloution_y = QtWidgets.QSpinBox(self.tab_SLM)
        self.spinBox_SLMdisresloution_y.setGeometry(QtCore.QRect(175, 152, 60, 27))
        self.spinBox_SLMdisresloution_y.setMaximum(20000)
        self.spinBox_SLMdisresloution_y.setMinimum(0)
        self.spinBox_SLMdisresloution_y.setValue(1080)
        self.spinBox_SLMdisresloution_y.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_SLMdisresloution_y.setObjectName("spinBox_SLMdisresloution_y")

        self.spinBox_Camsavefre = QtWidgets.QSpinBox(self.groupBox_camimgsave)
        self.spinBox_Camsavefre.setGeometry(QtCore.QRect(20, 100, 60, 27))
        self.spinBox_Camsavefre.setMaximum(200)
        self.spinBox_Camsavefre.setMinimum(1)
        self.spinBox_Camsavefre.setValue(20)
        self.spinBox_Camsavefre.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_Camsavefre.setObjectName("spinBox_Camsavefre")

        self.spinBox_Camsavenb = QtWidgets.QSpinBox(self.groupBox_camimgsave)
        self.spinBox_Camsavenb.setGeometry(QtCore.QRect(20, 150, 60, 27))
        self.spinBox_Camsavenb.setMaximum(1000000)
        self.spinBox_Camsavenb.setMinimum(1)
        self.spinBox_Camsavenb.setValue(1000)
        self.spinBox_Camsavenb.setButtonSymbols(QtWidgets.QSpinBox.NoButtons)
        self.spinBox_Camsavenb.setObjectName("spinBox_Camsavenb")



        self.label_DMDdisfre = QtWidgets.QLabel(self.tab_DMD)
        self.label_DMDdisfre.setGeometry(QtCore.QRect(10, 95, 70, 21))
        self.label_DMDdisfre.setObjectName("label_DMDdisfre ")

        self.label_SLMdisfre = QtWidgets.QLabel(self.tab_SLM)
        self.label_SLMdisfre.setGeometry(QtCore.QRect(10, 95, 70, 21))
        self.label_SLMdisfre.setObjectName("label_SLMdisfre ")

        self.label_SLMdislocation = QtWidgets.QLabel(self.tab_SLM)
        self.label_SLMdislocation.setGeometry(QtCore.QRect(10, 125, 70, 21))
        self.label_SLMdislocation.setObjectName("label_SLMdislocation ")

        self.label_SLMdisresloution = QtWidgets.QLabel(self.tab_SLM)
        self.label_SLMdisresloution.setGeometry(QtCore.QRect(10, 155, 70, 21))
        self.label_SLMdisresloution.setObjectName("label_SLMdisresloution ")

        self.label_SLMdislocation_X = QtWidgets.QLabel(self.tab_SLM)
        self.label_SLMdislocation_X.setGeometry(QtCore.QRect(155, 125, 10, 21))
        self.label_SLMdislocation_X.setObjectName("label_SLMdislocation_X ")

        self.label_SLMdisresloution_X = QtWidgets.QLabel(self.tab_SLM)
        self.label_SLMdisresloution_X.setGeometry(QtCore.QRect(155, 155, 10, 21))
        self.label_SLMdisresloution_X.setObjectName("label_SLMdislocation ")

        self.label_X = QtWidgets.QLabel(self.tab_ImgGene)
        self.label_X.setGeometry(QtCore.QRect(293, 18, 10, 21))
        self.label_X.setObjectName("label_X ")

        self.pushButton_ManualDisconnectDMD = QtWidgets.QPushButton(self.tab_DMD)
        self.pushButton_ManualDisconnectDMD.setGeometry(QtCore.QRect(133, 20, 120, 31))
        self.pushButton_ManualDisconnectDMD.setObjectName(
            "pushButton_ManualDisconnectDMD"
        )

        self.pushButton_uptoSLM = QtWidgets.QPushButton(self.tab_SLM)
        self.pushButton_uptoSLM.setGeometry(QtCore.QRect(10, 180, 101, 28))
        self.pushButton_uptoSLM.setObjectName("pushButton_uptoSLM")

        self.pushButton_connectSLM = QtWidgets.QPushButton(self.tab_SLM)
        self.pushButton_connectSLM.setGeometry(QtCore.QRect(10, 20, 120, 31))
        self.pushButton_connectSLM.setObjectName("pushButton_connectSLM")

        self.pushButton_playSLM = QtWidgets.QPushButton(self.tab_SLM)
        self.pushButton_playSLM.setGeometry(QtCore.QRect(133, 20, 120, 31))
        self.pushButton_playSLM.setObjectName("pushButton_playSLM")

        self.label_SeqL = QtWidgets.QLabel(self.tab_ImgGene)
        self.label_SeqL.setGeometry(QtCore.QRect(10, 18, 70, 21))
        self.label_SeqL.setObjectName("label_SeqL ")

        self.label_Seqresolution = QtWidgets.QLabel(self.tab_ImgGene)
        self.label_Seqresolution.setGeometry(QtCore.QRect(140, 18, 80, 21))
        self.label_Seqresolution.setObjectName("label_Seqresolution ")

        self.label_Seqloadinf = QtWidgets.QLabel(self.centralwidget)
        self.label_Seqloadinf.setGeometry(QtCore.QRect(1400, 597, 220, 21))
        self.label_Seqloadinf.setObjectName("label_Seqloadinf")

        self.label_ImgOpeninf = QtWidgets.QLabel(self.tab_ImgOpen)
        self.label_ImgOpeninf.setGeometry(QtCore.QRect(20, 67, 220, 21))
        self.label_ImgOpeninf.setObjectName("label_ImgOpeninf")

        self.label_ImgOpeninginf = QtWidgets.QLabel(self.tab_ImgOpen)
        self.label_ImgOpeninginf.setGeometry(QtCore.QRect(40, 145, 220, 21))
        self.label_ImgOpeninginf.setObjectName("label_ImgOpeninginf")






        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(700, 0, 221, 171))
        self.groupBox.setObjectName("groupBox")

        self.groupBox1 = QtWidgets.QGroupBox(self.tab_CAM2)
        self.groupBox1.setGeometry(QtCore.QRect(695, 0, 221, 171))
        self.groupBox1.setObjectName("groupBox1")

        self.comboBox_CameraList = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_CameraList.setGeometry(QtCore.QRect(10, 70, 201, 31))
        self.comboBox_CameraList.setObjectName("comboBox_CameraList")

        self.comboBox_CameraList1 = QtWidgets.QComboBox(self.groupBox1)
        self.comboBox_CameraList1.setGeometry(QtCore.QRect(10, 70, 201, 31))
        self.comboBox_CameraList1.setObjectName("comboBox_CameraList1")

        self.pushButton_UpdateCameraList = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_UpdateCameraList.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.pushButton_UpdateCameraList.setObjectName("pushButton_UpdateCameraList")

        self.pushButton_UpdateCameraList1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_UpdateCameraList1.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.pushButton_UpdateCameraList1.setObjectName("pushButton_UpdateCameraList1")

        self.pushButton_OpenCamera = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_OpenCamera.setGeometry(QtCore.QRect(10, 110, 101, 28))
        self.pushButton_OpenCamera.setObjectName("pushButton_OpenCamera")

        self.pushButton_OpenCamera1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_OpenCamera1.setGeometry(QtCore.QRect(10, 110, 101, 28))
        self.pushButton_OpenCamera1.setObjectName("pushButton_OpenCamera1")

        self.pushButton_CloseCamera = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_CloseCamera.setGeometry(QtCore.QRect(110, 110, 101, 28))
        self.pushButton_CloseCamera.setObjectName("pushButton_CloseCamera")

        self.pushButton_CloseCamera1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_CloseCamera1.setGeometry(QtCore.QRect(110, 110, 101, 28))
        self.pushButton_CloseCamera1.setObjectName("pushButton_CloseCamera1")

        self.pushButton_StartAcq = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_StartAcq.setGeometry(QtCore.QRect(10, 140, 101, 28))
        self.pushButton_StartAcq.setObjectName("pushButton_StartAcq")

        self.pushButton_StartAcq1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_StartAcq1.setGeometry(QtCore.QRect(10, 140, 101, 28))
        self.pushButton_StartAcq1.setObjectName("pushButton_StartAcq1")

        self.pushButton_StopAcq = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_StopAcq.setGeometry(QtCore.QRect(110, 140, 101, 28))
        self.pushButton_StopAcq.setObjectName("pushButton_StopAcq")

        self.pushButton_StopAcq1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_StopAcq1.setGeometry(QtCore.QRect(110, 140, 101, 28))
        self.pushButton_StopAcq1.setObjectName("pushButton_StopAcq1")

        self.pushButton_ZoomIn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ZoomIn.setGeometry(QtCore.QRect(510, 10, 92, 28))
        self.pushButton_ZoomIn.setObjectName("pushButton_ZoomIn")
        self.pushButton_ZoomOut = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ZoomOut.setGeometry(QtCore.QRect(600, 10, 92, 28))
        self.pushButton_ZoomOut.setObjectName("pushButton_ZoomOut")

        self.pushButton_ZoomIn1 = QtWidgets.QPushButton(self.tab_CAM2)
        self.pushButton_ZoomIn1.setGeometry(QtCore.QRect(505, 10, 92, 28))
        self.pushButton_ZoomIn1.setObjectName("pushButton_ZoomIn1")
        self.pushButton_ZoomOut1 = QtWidgets.QPushButton(self.tab_CAM2)
        self.pushButton_ZoomOut1.setGeometry(QtCore.QRect(595, 10, 92, 28))
        self.pushButton_ZoomOut1.setObjectName("pushButton_ZoomOut1")

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(700, 170, 221, 111))
        self.groupBox_2.setObjectName("groupBox_2")

        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_CAM2)
        self.groupBox_21.setGeometry(QtCore.QRect(695, 170, 221, 111))
        self.groupBox_21.setObjectName("groupBox_21")

        self.comboBox_ExposureMode = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_ExposureMode.setGeometry(QtCore.QRect(120, 20, 91, 22))
        self.comboBox_ExposureMode.setObjectName("comboBox_ExposureMode")

        self.comboBox_ExposureMode1 = QtWidgets.QComboBox(self.groupBox_21)
        self.comboBox_ExposureMode1.setGeometry(QtCore.QRect(120, 20, 91, 22))
        self.comboBox_ExposureMode1.setObjectName("comboBox_ExposureMode1")

        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label.setObjectName("label")

        self.label1 = QtWidgets.QLabel(self.groupBox_21)
        self.label1.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label1.setObjectName("label1")

        self.comboBox_ExposureAuto = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_ExposureAuto.setGeometry(QtCore.QRect(120, 50, 91, 22))
        self.comboBox_ExposureAuto.setObjectName("comboBox_ExposureAuto")

        self.comboBox_ExposureAuto1 = QtWidgets.QComboBox(self.groupBox_21)
        self.comboBox_ExposureAuto1.setGeometry(QtCore.QRect(120, 50, 91, 22))
        self.comboBox_ExposureAuto1.setObjectName("comboBox_ExposureAuto1")

        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_2.setObjectName("label_2")

        self.label_21 = QtWidgets.QLabel(self.groupBox_21)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_21.setObjectName("label_21")

        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_3.setObjectName("label_3")

        self.label_31 = QtWidgets.QLabel(self.groupBox_21)
        self.label_31.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_31.setObjectName("label_31")

        self.doubleSpinBox_ExposureTime = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_ExposureTime.setGeometry(QtCore.QRect(120, 80, 91, 22))
        self.doubleSpinBox_ExposureTime.setMaximum(99999999.99)
        self.doubleSpinBox_ExposureTime.setObjectName("doubleSpinBox_ExposureTime")

        self.doubleSpinBox_ExposureTime1 = QtWidgets.QDoubleSpinBox(self.groupBox_21)
        self.doubleSpinBox_ExposureTime1.setGeometry(QtCore.QRect(120, 80, 91, 22))
        self.doubleSpinBox_ExposureTime1.setMaximum(99999999.99)
        self.doubleSpinBox_ExposureTime1.setObjectName("doubleSpinBox_ExposureTime1")






        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(700, 280, 221, 131))
        self.groupBox_3.setObjectName("groupBox_3")

        self.groupBox_31 = QtWidgets.QGroupBox(self.tab_CAM2)
        self.groupBox_31.setGeometry(QtCore.QRect(695, 280, 221, 131))
        self.groupBox_31.setObjectName("groupBox_31")

        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_6.setObjectName("label_6")

        self.label_61 = QtWidgets.QLabel(self.groupBox_31)
        self.label_61.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_61.setObjectName("label_61")

        self.comboBox_TriggerMode = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_TriggerMode.setGeometry(QtCore.QRect(120, 20, 91, 22))
        self.comboBox_TriggerMode.setObjectName("comboBox_TriggerMode")

        self.comboBox_TriggerMode1 = QtWidgets.QComboBox(self.groupBox_31)
        self.comboBox_TriggerMode1.setGeometry(QtCore.QRect(120, 20, 91, 22))
        self.comboBox_TriggerMode1.setObjectName("comboBox_TriggerMode1")

        self.comboBox_TriggerSource = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_TriggerSource.setGeometry(QtCore.QRect(120, 50, 91, 22))
        self.comboBox_TriggerSource.setObjectName("comboBox_TriggerSource")

        self.comboBox_TriggerSource1 = QtWidgets.QComboBox(self.groupBox_31)
        self.comboBox_TriggerSource1.setGeometry(QtCore.QRect(120, 50, 91, 22))
        self.comboBox_TriggerSource1.setObjectName("comboBox_TriggerSource1")

        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_7.setObjectName("label_7")

        self.label_71 = QtWidgets.QLabel(self.groupBox_31)
        self.label_71.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_71.setObjectName("label_71")

        self.pushButton_SendSoftwareCommand = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_SendSoftwareCommand.setGeometry(QtCore.QRect(10, 80, 201, 41))
        self.pushButton_SendSoftwareCommand.setObjectName("pushButton_SendSoftwareCommand")

        self.pushButton_SendSoftwareCommand1 = QtWidgets.QPushButton(self.groupBox_31)
        self.pushButton_SendSoftwareCommand1.setGeometry(QtCore.QRect(10, 80, 201, 41))
        self.pushButton_SendSoftwareCommand1.setObjectName("pushButton_SendSoftwareCommand1")

        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(700, 410, 221, 81))
        self.groupBox_4.setObjectName("groupBox_4")

        self.groupBox_41 = QtWidgets.QGroupBox(self.tab_CAM2)
        self.groupBox_41.setGeometry(QtCore.QRect(695, 410, 221, 81))
        self.groupBox_41.setObjectName("groupBox_41")

        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_8.setObjectName("label_8")

        self.label_81 = QtWidgets.QLabel(self.groupBox_41)
        self.label_81.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_81.setObjectName("label_81")

        self.comboBox_GainAuto = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_GainAuto.setGeometry(QtCore.QRect(120, 20, 91, 22))
        self.comboBox_GainAuto.setObjectName("comboBox_GainAuto")

        self.comboBox_GainAuto1 = QtWidgets.QComboBox(self.groupBox_41)
        self.comboBox_GainAuto1.setGeometry(QtCore.QRect(120, 20, 91, 22))
        self.comboBox_GainAuto1.setObjectName("comboBox_GainAuto1")

        self.doubleSpinBox_GainValue = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_GainValue.setGeometry(QtCore.QRect(120, 50, 91, 22))
        self.doubleSpinBox_GainValue.setMaximum(99999999.99)
        self.doubleSpinBox_GainValue.setObjectName("doubleSpinBox_GainValue")

        self.doubleSpinBox_GainValue1 = QtWidgets.QDoubleSpinBox(self.groupBox_41)
        self.doubleSpinBox_GainValue1.setGeometry(QtCore.QRect(120, 50, 91, 22))
        self.doubleSpinBox_GainValue1.setMaximum(99999999.99)
        self.doubleSpinBox_GainValue1.setObjectName("doubleSpinBox_GainValue1")

        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_9.setObjectName("label_9")

        self.label_91 = QtWidgets.QLabel(self.groupBox_41)
        self.label_91.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_91.setObjectName("label_91")

        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(1400, 690, 221, 61))
        self.pushButton_close.setObjectName("pushButton_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "CameraControl"))
        self.pushButton_UpdateCameraList.setText(_translate("MainWindow", "UpdateCameraList"))
        self.pushButton_OpenCamera.setText(_translate("MainWindow", "OpenCamera"))
        self.pushButton_CloseCamera.setText(_translate("MainWindow", "CloseCamera"))
        self.pushButton_StartAcq.setText(_translate("MainWindow", "StartAcq"))
        self.pushButton_StopAcq.setText(_translate("MainWindow", "StopAcq"))
        self.pushButton_ZoomIn.setText(_translate("MainWindow", "ZoomIn"))
        self.pushButton_ZoomOut.setText(_translate("MainWindow", "ZoomOut"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Exposure"))
        self.label.setText(_translate("MainWindow", "ExposureMode:"))
        self.label_2.setText(_translate("MainWindow", "ExposureAuto:"))
        self.label_3.setText(_translate("MainWindow", "ExposureTime:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Trigger"))
        self.label_6.setText(_translate("MainWindow", "TriggerMode:"))
        self.label_7.setText(_translate("MainWindow", "TriggerSource:"))
        self.pushButton_SendSoftwareCommand.setText(_translate("MainWindow", "SendSoftwareCommand"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Gain"))
        self.label_8.setText(_translate("MainWindow", "GainAuto:"))
        self.label_9.setText(_translate("MainWindow", "GainVlue:"))
        self.pushButton_close.setText(_translate("MainWindow", "关闭"))

        self.groupBox1.setTitle(_translate("MainWindow", "CameraControl"))
        self.pushButton_UpdateCameraList1.setText(_translate("MainWindow", "UpdateCameraList"))
        self.pushButton_OpenCamera1.setText(_translate("MainWindow", "OpenCamera"))
        self.pushButton_CloseCamera1.setText(_translate("MainWindow", "CloseCamera"))
        self.pushButton_StartAcq1.setText(_translate("MainWindow", "StartAcq"))
        self.pushButton_StopAcq1.setText(_translate("MainWindow", "StopAcq"))
        self.pushButton_ZoomIn1.setText(_translate("MainWindow", "ZoomIn"))
        self.pushButton_ZoomOut1.setText(_translate("MainWindow", "ZoomOut"))
        self.groupBox_21.setTitle(_translate("MainWindow", "Exposure"))
        self.label1.setText(_translate("MainWindow", "ExposureMode:"))
        self.label_21.setText(_translate("MainWindow", "ExposureAuto:"))
        self.label_31.setText(_translate("MainWindow", "ExposureTime:"))
        self.groupBox_31.setTitle(_translate("MainWindow", "Trigger"))
        self.label_61.setText(_translate("MainWindow", "TriggerMode:"))
        self.label_71.setText(_translate("MainWindow", "TriggerSource:"))
        self.pushButton_SendSoftwareCommand1.setText(_translate("MainWindow", "SendSoftwareCommand"))
        self.groupBox_41.setTitle(_translate("MainWindow", "Gain"))
        self.label_81.setText(_translate("MainWindow", "GainAuto:"))
        self.label_91.setText(_translate("MainWindow", "GainVlue:"))

        self.label_BlockW.setText(_translate("MainWindow", "块宽度："))
        self.label_SeqL.setText(_translate("MainWindow", "序列长度："))
        self.label_Seqresolution.setText(_translate("MainWindow", "序列分辨率："))
        self.label_X.setText(_translate("MainWindow", "X"))
        self.groupBox_camimgsave.setTitle(_translate("MainWindow", "CCD1采集"))
        self.groupBox_camimgsave1.setTitle(_translate("MainWindow", "CCD2采集"))

        self.label_Seqloadinf.setText(_translate("MainWindow", "当前序列：空序列"))
        self.label_DMDdisfre.setText(_translate("MainWindow", "显示频率："))
        self.label_SLMdisfre.setText(_translate("MainWindow", "显示频率："))
        self.label_SLMdislocation.setText(_translate("MainWindow", "位置："))
        self.label_SLMdisresloution.setText(_translate("MainWindow", "大小："))

        self.pushButton_InitializetheDMD.setText(_translate("MainWindow", "连接DMD"))
        self.pushButton_UptoDMD.setText(_translate("MainWindow", "加载至DMD内存"))
        self.pushButton_cleanDMD.setText(_translate("MainWindow", "清空DMD内存"))
        self.pushButton_runDMD.setText(_translate("MainWindow", "开始显示"))
        self.pushButton_stopDMD.setText(_translate("MainWindow", "中断显示"))
        self.pushButton_ImgSeqGenerate.setText(_translate("MainWindow", "生成图片"))
        self.pushButton_ImgSeqOpen.setText(_translate("MainWindow", "打开图片"))
        self.pushButton_SelectSavePathofImgSeqGenerate.setText(
            _translate("MainWindow", "浏览")
        )
        self.pushButton_SelectOpenPathofImgSeqGenerate.setText(
            _translate("MainWindow", "浏览")
        )
        self.pushButton_SelecttheSavePathofCamImg.setText(
            _translate("MainWindow", "浏览")
        )

        self.pushButton_SelecttheSavePathofCamImg1.setText(
            _translate("MainWindow", "浏览")
        )
        self.pushButton_StartCamImgSave.setText(_translate("MainWindow", "开始采集"))
        self.pushButton_StartCamImgSave1.setText(_translate("MainWindow", "开始采集"))
        self.pushButton_StopCamImgSave.setText(_translate("MainWindow", "停止采集"))
        self.pushButton_StopCamImgSave1.setText(_translate("MainWindow", "停止采集"))
        self.pushButton_ManualDisconnectDMD.setText(_translate("MainWindow", "断开连接DMD"))
        self.pushButton_uptoSLM.setText(_translate("MainWindow", "上传至SLM"))
        self.pushButton_connectSLM.setText(_translate("MainWindow", "连接SLM"))
        self.pushButton_playSLM.setText(_translate("MainWindow", "播放SLM"))
        self.label_DMDIni.setText(_translate("MainWindow", "DMD未连接"))
        self.label_SLMdislocation_X.setText(_translate("MainWindow", ","))
        self.label_SLMdisresloution_X.setText(_translate("MainWindow", "X"))

        self.label_PreImgGene.setText(_translate("MainWindow", ""))
        self.label_PreImgOpen.setText(_translate("MainWindow", ""))
        self.label_PreImgGenetext.setText(_translate("MainWindow", "块宽度预览："))
        self.label_ImgGeneinf.setText(_translate("MainWindow", ""))
        self.label_ImgOpeninginf.setText(_translate("MainWindow", ""))



        self.label_PMinf.setText(_translate("MainWindow", "pminf"))
        self.label_PMdev.setText(_translate("MainWindow", "功率计："))
        self.label_PMwavelength.setText(_translate("MainWindow", "波长："))
        self.label_PMwavelengthnm.setText(_translate("MainWindow", "nm"))
        self.label_PMmeasure.setText(_translate("MainWindow", "   N/A"))
        self.label_PMwl2dis.setText(_translate("MainWindow", " "))
        self.pushButton_refreshPMdev.setText(_translate("MainWindow", "刷新"))
        self.pushButton_connectPMdev.setText(_translate("MainWindow", "连接"))
        self.pushButton_disconnectPMdev.setText(_translate("MainWindow", "关闭设备"))
        self.groupBox_powerdis.setTitle(_translate("MainWindow", "功率："))






        self.label_CCD_CatchSpeed.setText(_translate("MainWindow", "采集频率（张/s）"))
        self.label_CCD_CatchTime.setText(_translate("MainWindow", "采集张数（张）"))
        self.label_DMDInformation.setText(_translate("MainWindow", ""))
        self.label_SLMInformation.setText(_translate("MainWindow", "SLM未连接"))
        self.label_ImgOpeninf.setText(_translate("MainWindow", ""))